services:
  app:
    build: .
    ports:
      - "8080:8080"
    working_dir: /app
    command: [ "java", "-jar", "spring_jpa.jar" ]
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/myDb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING.DATASOURCE.DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myDb
      MYSQL_USER: 123
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
