services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /app
    command: [ "java", "-jar", "spring_jpa.jar" ]
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/myDb
      - spring.datasource.username=root
      - spring.datasource.password=123
    depends_on:
      - db
  db:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=myDb
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d # Mount the init-scripts directory
