version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
  app:
    image: your-image-name # Replace with the name of the Docker image you built
    ports:
      - "8080:8080"
    container_name: springboot-container
    restart: always
